package xhtml

const (
	HTML     = "html"
	TITLE    = "title"
	HEAD     = "head"
	BODY     = "body"
	HEADER   = "header"
	FOOTER   = "footer"
	MAIN     = "main"
	SECTION  = "section"
	DIV      = "div"
	SPAN     = "span"
	P        = "p"
	A        = "a"
	HREF     = "href"
	BR       = "br"
	HR       = "hr"
	UL       = "ul"
	LI       = "li"
	H1       = "h1"
	H2       = "h2"
	H3       = "h3"
	H4       = "h4"
	H5       = "h5"
	H6       = "h6"
	STRONG   = "strong"
	EM       = "em"
	SMALL    = "small"
	MARK     = "mark"
	DEL      = "del"
	INS      = "ins"
	IMG      = "img"
	SRC      = "src"
	FIGURE   = "figure"
	TABLE    = "table"
	TR       = "tr"
	TD       = "td"
	TH       = "th"
	FORM     = "form"
	INPUT    = "input"
	TEXTAREA = "textarea"
	BUTTON   = "button"
	SELECT   = "select"
	OPTION   = "option"
)
